### ISSUE TITLE
one click deployment is not working well, please fix it promptly

### ISSUE THREAD

**Issue by Suremotoo** [web3templates/sandocs-template#1]
The 'Deploy Vercel & Sanity' buttons in the README file cannot be used properly.

**Comment by surjithctly** [comment]
You can use the [Vercel Deploy](https://vercel.com/new/brilla/clone?repository-url=https://github.com/web3templates/sandocs-template&integration-ids=oac_hb2LITYajhRQ0i4QznmKH7gx) instead.

Readme is also updated. Thank you!
